[package]
name = "torus-network"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
torus-types = { workspace = true }
torus-telemetry = { workspace = true }
hotstuff_rs = { workspace = true }
ed25519-dalek = { workspace = true }
borsh = "0.10"  # must match hotstuff_rs borsh version
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
libp2p = { workspace = true }
sha3 = { workspace = true }
bincode = { workspace = true }
zeroize = { workspace = true }
futures = "0.3"
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
tempfile = { workspace = true }
hex = { workspace = true }
