[package]
name = "torus-rpc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
torus-types = { workspace = true }
torus-state = { workspace = true }
torus-mempool = { workspace = true }
torus-evm = { workspace = true }
torus-core = { workspace = true }
torus-economics = { workspace = true }
jsonrpsee = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
tracing = { workspace = true }
borsh = { workspace = true }
rocksdb = { workspace = true }
hex = "0.4"
thiserror = "2"

[dev-dependencies]
tempfile = { workspace = true }
revm = { workspace = true }
k256 = { workspace = true }
sha3 = { workspace = true }
