[package]
name = "torus-consensus"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
torus-types = { workspace = true }
torus-state = { workspace = true }
torus-evm = { workspace = true }
torus-bridge = { workspace = true }
torus-economics = { workspace = true }
hotstuff_rs = { workspace = true }
rocksdb = { workspace = true }
serde_json = { workspace = true }
ed25519-dalek = { workspace = true }
sha2 = "0.10"
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
