#!/usr/bin/env python3
# p3s-handoff-tables.py: READ-ONLY extraction of raw numbers for the ozarchy-p3s handoff (numbers only: no ranking, no verdict).
# Usage: python3 -I p3s-handoff-tables.py > handoff-tables.txt
import glob
import json
import os
import re

R = "/home/oz/bench-results-matched"
P = "ozarchy-p3s-300m"
TAGS = ["tw-r1", "tw-r2", "tw-old1", "tw-c1", "tw-c2", "tw-c3", "tw-p1", "tw-p2"]
CAMP = os.path.join(R, "ozarchy-p3s-run", "campaign.log")
ANSI = re.compile(r"\x1b\[[0-9;]*m")

camp = open(CAMP, errors="replace").read().splitlines()


def rd(path):
    try:
        with open(path, errors="replace") as f:
            return f.read()
    except OSError:
        return None


def jl(path):
    t = rd(path)
    return json.loads(t) if t else None


print(
    "# ozarchy-p3s handoff tables (raw numbers, read-only extraction of cell dirs; generated by p3s-handoff-tables.py)"
)
print(
    "# cell dirs: %s/%s-<tag>/ ; control tw-old1 = acc3 node 2ede76eb (same tw knobs); tw-c* = multi-crash (kills 60,180,300 s, val1)"
    % (R, P)
)
print()
print("## per cell")
hdr = "tag|rc|CHECK_OK|node_exe_md5|bench_wall_s|matched_s_avg|placed_s_avg|native_blk_s|blk_s_avg|agreement|val0_user_ms|val0_sys_ms|val0_native_blocks|val0_fills|val1_user_ms|val1_sys_ms|val2_user_ms|val2_sys_ms|perf_data_MB"
print(hdr)
per = {}
for t in TAGS:
    label = "%s-%s" % (P, t)
    d = os.path.join(R, label)
    rc = (
        (rd(os.path.join(R, label + ".cell.rc")) or "rc=missing")
        .strip()
        .replace("rc=", "")
    )
    ok = sum(
        1
        for l in camp
        if l.startswith("CHECK OK " + label + " ")
        or (" " + label + " ") in l
        and "CHECK OK" in l
    )
    s = jl(os.path.join(d, "summary.json")) or {}
    h = s.get("headline", {})
    tim = s.get("timing", {})
    pcn = s.get("proc_cpu_by_node", {}) or {}

    def wr(n, k):
        return (pcn.get(n, {}) or {}).get("whole_run", {}).get(k, "")

    trie = rd(os.path.join(d, "node-environ-trie.txt")) or ""
    md5s = sorted(set(re.findall(r"exe_md5=([0-9a-f]+)", trie)))
    perf = os.path.join(d, "perf.data")
    perf_mb = "%.1f" % (os.path.getsize(perf) / 1048576) if os.path.exists(perf) else ""
    row = [
        t,
        rc,
        str(ok),
        ",".join(md5s),
        str(tim.get("bench_wall_s", "")),
        str(h.get("matched_s_avg", "")),
        str(h.get("placed_s_avg", "")),
        str(h.get("native_blk_s", "")),
        str(h.get("blk_s_avg", "")),
        str(h.get("agreement_verdict", "")),
        str(wr("val0", "user_ms")),
        str(wr("val0", "sys_ms")),
        str(wr("val0", "native_blocks")),
        str(wr("val0", "fills")),
        str(wr("val1", "user_ms")),
        str(wr("val1", "sys_ms")),
        str(wr("val2", "user_ms")),
        str(wr("val2", "sys_ms")),
        perf_mb,
    ]
    print("|".join(row))
    per[t] = h
print()
print(
    "## per arm (throughput replicates: tw-r1, tw-r2 on fd9e5dfa; tw-old1 control on acc3 node)"
)
for name, tags in [
    ("tw fd9e5dfa", ["tw-r1", "tw-r2"]),
    ("tw control acc3 node", ["tw-old1"]),
]:
    vals = [
        per[t].get("matched_s_avg")
        for t in tags
        if per.get(t, {}).get("matched_s_avg") is not None
    ]
    if vals:
        mean = sum(vals) / len(vals)
        print(
            "%s: matched_s_avg n=%d mean=%.1f spread(max-min)=%.1f values=%s"
            % (name, len(vals), mean, max(vals) - min(vals), vals)
        )
print()
print("## crash cells: per kill (run.log 'crash gate scan' + crash-kill record)")
for t in ["tw-c1", "tw-c2", "tw-c3"]:
    label = "%s-%s" % (P, t)
    d = os.path.join(R, label)
    run = rd(os.path.join(d, "run.log")) or ""
    for l in ANSI.sub("", run).splitlines():
        if l.startswith("crash gate scan:") or "crash gate: kill " in l:
            print("%s: %s" % (t, l[:220]))
    for rec in sorted(glob.glob(os.path.join(d, "crash-kill*.json"))):
        j = jl(rec) or {}
        print(
            "%s: %s kill_seq=%s down_s=%s kill_ts=%s restart_ts=%s db_open? restart_keys=%s"
            % (
                t,
                os.path.basename(rec),
                j.get("kill_seq"),
                j.get("down_s"),
                j.get("kill_ts"),
                j.get("restart_ts"),
                ",".join(sorted(j.keys()))[:160],
            )
        )
print()
print("## WAL keep (tw-r1, val0): hard-linked WAL files in wal-val0-keep/")
k = os.path.join(R, P + "-tw-r1", "wal-val0-keep")
files = (
    sorted(f for f in os.listdir(k) if f.endswith(".log")) if os.path.isdir(k) else []
)
size = sum(os.path.getsize(os.path.join(k, f)) for f in files)
miss = rd(os.path.join(k, "miss.txt")) or ""
print(
    "files=%d bytes=%d first=%s last=%s miss_lines=%d"
    % (
        len(files),
        size,
        files[0] if files else "",
        files[-1] if files else "",
        len(miss.splitlines()),
    )
)
